name: Push to Another Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: main
          remote_repository: https://github.com/icrwly/ulsource.git
          access_token: ${{secrets.IPC}}
          force: true
