name: Push to Another Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output DESTINATION_REPO_PAT
        run: echo "IPC is $IPC"
        env:
          DESTINATION_REPO_PAT: ${{ secrets.IPC }}

      - name: Push Code to Destination Repository
        run: |
          git remote add destination https://$DESTINATION_GITHUB_USERNAME:${{ secrets.DESTINATION_REPO_PAT }}@github.com/$DESTINATION_GITHUB_USERNAME/$DESTINATION_REPO_NAME.git
          git push destination main
        env:
          DESTINATION_GITHUB_USERNAME: icrwly
          DESTINATION_REPO_NAME: ulsource
