name: Build and Deploy Assets
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Assets
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          target_owner: icrwly
          target_repo: ulsource
          target_branch: main # default
          # Optional
          access_token: ${{ secrets.IPC }}
